version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        container_name: educative_db
        env_file: 
          - .env
        environment:
          - POSTGRES_USER=$POSTGRES_USER
          - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          - POSTGRES_DB=$POSTGRES_DATABASE 
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '$POSTGRES_PORT:$POSTGRES_PORT_DOCKER'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sq